AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.6
  DisabledByDefault: false 
  
Style/WordArray:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false
  
Lint/UselessAssignment:
  Enabled: false
