# Включить все Ruby файлы для анализа
include:
  - "**/*.rb"

# Исключить определенные директории, например, тесты и файлы, установленные через bundle
exclude:
  - "spec/**/*"
  - "test/**/*"
  - "vendor/**/*"
  - ".bundle/**/*"

# Зависимости, которые необходимо подгрузить
require: []

# Домены, которые Solargraph должен индексировать (оставьте пустым, если не уверены)
domains: []

# Репортеры для оповещений, как RuboCop или сообщения об отсутствии require
reporters:
  - rubocop
  - require_not_found

# Настройки для RuboCop
formatter:
  rubocop:
    cops: safe  # Уровень проверок для RuboCop, safe или aggressive
    except: []  # Исключить конкретные проверки
    only: []    # Включить только определенные проверки
    extra_args: []  # Дополнительные аргументы командной строки

# Пути, которые Solargraph должен добавить для загрузки
require_paths: []

# Плагины для Solargraph
plugins: []

# Максимальное количество файлов для индексации
max_files: 5000
